name: Deployment Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

env:
  BUILD_NUMBER: release

jobs:
  Build-RC:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Commit Stage Tests + Package
        run: mvn -B package

      - name: DockerHub > login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: DockerHub > push (${{ env.BUILD_NUMBER }})
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ravenscore:${{ env.BUILD_NUMBER }}

      - name: Deploy
        run: >
          sshpass -p "${{ secrets.VPS_PASS }}" ssh -o "StrictHostKeyChecking no" root@${{ secrets.VPS_IP }} "
          docker stop ravenscore || true; 
          docker rm ravenscore || true; 
          docker image prune -a -f; 
          docker pull ${{ secrets.DOCKER_USERNAME }}/ravenscore:${{ env.BUILD_NUMBER }}; 
          docker run -d -p 8081:8081 --name ravenscore --add-host host.docker.internal:host-gateway \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASS=${{ secrets.DB_PASS }} \
            -e DB_URL=host.docker.internal/ravenscore \
            ${{ secrets.DOCKER_USERNAME }}/ravenscore:${{ env.BUILD_NUMBER }}
          "